version: "3.8"

services:
  vitalya:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # Start the agent with the latest version
    networks:
      - traefik-hub
  hub-agent:
      image: ghcr.io/traefik/hub-agent-traefik:v1.0.0
      pull_policy: always
      container_name: hub-agent
      restart: "on-failure"
      command:
        - run
        - --hub.token=aac69952-7fb8-44b2-b1b7-3cd9634fc19f
        - --auth-server.advertise-url=http://hub-agent
        - --traefik.host=traefik
        - --traefik.tls.insecure=true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - traefik-hub
      depends_on:
        - traefik

    # Start Traefik with the latest version
  traefik:
      image: traefik:v2.9
      container_name: traefik
      command:
        # Enable Hub communication (open the port 9900 and 9901 by default)
        - --experimental.hub=true
        - --hub.tls.insecure=true
        - --metrics.prometheus.addrouterslabels=true
      networks:
        - traefik-hub

networks:
    traefik-hub: {}
